# This config file for Travis CI utilizes https://github.com/ros-planning/moveit_ci package.
sudo: required
dist: xenial
services:
  - docker
language: cpp
compiler: gcc
cache: ccache

notifications:
  email:
    recipients:

env:
  global:
    - ROS_DISTRO=melodic
    - UPSTREAM_WORKSPACE=.rosinstall/random_pick/random_pick.rosinstall
  matrix:
    - TEST=clang-format,catkin_lint
    - DOCKER_IMAGE=moveit/moveit:master-source   BEFORE_SCRIPT="source moveit_example_apps/.travis/random_pick/before_script.sh" 

before_install: 
  - sudo -E sh -c 'echo "deb http://packages.ros.org/ros/ubuntu `lsb_release -cs` main" > /etc/apt/sources.list.d/ros-latest.list'
  - wget http://packages.ros.org/ros.key -O - | sudo apt-key add -
  - sudo apt-get update -qq
  - sudo apt-get -qq install ros-kinetic-rosdoc-lite
  - source /opt/ros/kinetic/setup.bash
  - gem update --system
  - gem --version
  - gem install html-proofer

before_script:
  - git clone -q --depth=1 -b postpone-early-tests https://github.com/rhaschke/moveit_ci.git .moveit_ci
script:
  - .moveit_ci/travis.sh
  - cd tutorials
  - sphinx-build -W -b html . native_build
  - rosdoc_lite -o build .
  - htmlproofer ./build --only-4xx --check-html --file-ignore ./build/html/genindex.html,./build/html/search.html,./build/html/index-msg.html --alt-ignore '/.*/' --url-ignore '#'

after_success:
  - touch build/html/.nojekyll

deploy:
  # Deploy to gh-pages branch
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  local_dir: tutorials/build/html
  on:
    branch: random_pick_tutorial
